# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-kqGIPToDE4i1EJ9vz91Uxjl8jkcnPc
"""

pip install gensim

import gensim.downloader as api
from gensim.utils import simple_preprocess

def load_pretrained_word2vec():

    model = api.load("word2vec-google-news-300")
    return model

def get_word_embeddings(text, model):

    tokens = simple_preprocess(text)

    embeddings = {}
    for word in tokens:
        if word in model:
            embeddings[word] = model[word]

    return embeddings


if __name__ == "__main__":

    model = load_pretrained_word2vec()

    text = "Natural language processing enables machines to understand human language."

    word_embeddings = get_word_embeddings(text, model)

    for word, embedding in word_embeddings.items():
        print(f"Word: {word}, Embedding (first 5 dimensions): {embedding[:5]}")

