# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
   https://colab.research.google.com/drive/1LDzLJCeZ21Phurif7YFRRn51zkNunQ1_
"""

pip install nltk

import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
def nltk_tokenizer(text):
    tokens = word_tokenize(text)
    return tokens

text = "Hello, world! This is an NLTK tokenization example."
tokens = nltk_tokenizer(text)
print(tokens)

